# .github/workflows/deployment.yml
name: 'Deployment Pipeline'
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to production
        # Add your deployment commands here
        run: echo "Deploying to production..."